Filter encrypted attributes automatically
collectiveidea/audited pull request #630
Opened 2022-07-05 05:41 UTC by vlad-psh

Rails 7 introduces built-in attributes encryption: https://edgeguides.rubyonrails.org/active_record_encryption.html
Those are configured with `encrypts` keyword, eg: `encrypts :password`

Because these attributes are considered sensitive, we shouldn't write plain unencrypted values to our audits table by default.

2022-07-05 11:29 UTC, danielmorrison requested changes
This seems smart. Could you add a note to the README about this too?

2022-07-05 14:38 UTC, vlad-psh commented
@danielmorrison Thanks for comment!
I added small note to the README and also fixed specs for Rails < 7

2022-12-23 16:42 UTC, danielmorrison approved these changes

2022-12-23 16:42 UTC, merged

2022-12-23 21:51 UTC, dsinn reviewed
We don't use `config.audit_class` and we're still a long way from being able to use ActiveRecord encryption (Rails 7).